In [1]:
# Database integration from PostgreSQL into Pandas
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os



# establish a connection engine to your PostgreSQL database (source db)
# connection string format = (dialect+driver://username:password@host:port/database)

source_engine = create_engine("postgresql+psycopg2://postgres:QztLWcoQoMcFPKoKgCyuDwUPjOHUYdtO@trolley.proxy.rlwy.net:50067/railway")

In [2]:
# import and setting connection for Snowflake
from sqlalchemy import inspect
from sqlalchemy import text
from snowflake.sqlalchemy import URL

# connecting_string_format = create_engine("snowflake://username:password@account/database/schema?warehouse=warehouse&role=role")

load_dotenv()  # Loads variables from .env

# establishing destination connection engine using the snowflake.sqlalchemy.URL helper method
destination_engine = create_engine(
    URL(
        account="ydtdapw-ha47778",
        user="Nmadata",
        password=os.getenv("SNOWFLAKE_PASSWORD"),
        database="ELT_PIPELINE",
        schema="RAW",
        warehouse="ETL_WH",
        role="ACCOUNTADMIN",
    ) )

In [3]:
# testing connections for both source and destination configuration
try: 
    with source_engine.connect() as conn:
        print("postgres connection successful")
    with destination_engine.connect() as conn:
        print("snowflake connection Successful")
except Exception as e:
    print(f"Connection Error:{e}")

postgres connection successful
snowflake connection Successful

In [4]:
# inspect tables
inspector = inspect(source_engine)
source_tables = inspector.get_table_names(schema= 'public') # pulling from railways public schema in postgres

print(f"Found {len(source_tables)} tables in SQL Server: {source_tables}")

Found 10 tables in SQL Server: ['categories', 'products', 'customers', 'orders', 'coupons', 'order_items', 'payments', 'shipping', 'inventory', 'reviews']

In [5]:
# Extract data from one table with a query string
table = "categories"

query = f"""
SELECT *
FROM {table}
"""

df_table = pd.read_sql(query, source_engine)

In [6]:
df_table

,id,name,slug,is_active,created_at,updated_at
0,1,Electronics,electronics,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,Clothing,clothing,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,Books,books,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
3,4,Home & Kitchen,home-kitchen,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
4,5,Sports,sports,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [7]:
# load the first table into snowflake
table_name = f"raw_{table}" # prepend table prefix

print(f"writing {table_name} to snowflake ({len(df_table)} rows)")

df_table.to_sql(
          table_name,
          destination_engine,
          schema = 'raw',
          if_exists ='replace', # full refresh overwrite
          index=False
)

print(f"successfully moved {table_name}")

writing raw_categories to snowflake (5 rows)
successfully moved raw_categories

In [8]:
# extracting all 10 tables

In [9]:
tables = ['categories', 'products', 'customers', 'orders', 'coupons', 'order_items', 'payments', 'shipping', 'inventory', 'reviews']

In [10]:
df_tables = {}

for table in tables:
    query = f"""
        SELECT *
        FROM {table}
    """
    df_table = pd.read_sql(query, source_engine)
    df_tables[table] = df_table

In [11]:
df_tables['products']

,id,category_id,name,slug,description,price,image_url,is_active,created_at,updated_at
0,1,1,Samsung Galaxy A54,samsung-galaxy-a54,Mid-range Android smartphone,299.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,1,Wireless Earbuds Pro,wireless-earbuds-pro,Noise-cancelling wireless earbuds,49.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,1,USB-C Hub 7-in-1,usb-c-hub-7in1,Multiport USB-C adapter,35.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
3,4,1,Mechanical Keyboard,mechanical-keyboard,"TKL mechanical keyboard, red switches",79.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
4,5,2,Classic White Tee,classic-white-tee,100% cotton unisex t-shirt,15.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
5,6,2,Slim Fit Chinos,slim-fit-chinos,Comfortable slim-fit chino trousers,39.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
6,7,2,Puffer Jacket,puffer-jacket,Lightweight winter puffer jacket,89.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
7,8,3,Python for Data Analysis,python-data-analysis,Wes McKinney's pandas bible,42.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
8,9,3,Designing Data-Intensive Apps,ddia,Martin Kleppmann's systems classic,55.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
9,10,3,The Pragmatic Programmer,pragmatic-programmer,Hunt & Thomas — timeless software wisdom,38.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
10,11,4,Stainless Steel Blender,stainless-blender,1200W high-speed blender,65.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
11,12,4,Air Fryer 4L,air-fryer-4l,Digital air fryer with 8 presets,79.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
12,13,5,Yoga Mat 6mm,yoga-mat-6mm,Non-slip eco-friendly yoga mat,22.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
13,14,5,Adjustable Dumbbells,adjustable-dumbbells,5-25kg adjustable dumbbell pair,119.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
14,15,5,Running Shoes,running-shoes,Lightweight breathable running shoes,85.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [12]:
# load all tables to the staging schema in Snowflake and name the table as stg_

In [ ]:
# writing data to pandas and laoding it in snowflake
for tables, df in df_tables.items():
    table_name = f"raw_{tables}"

    print(f"Writing {table_name} to Snowflake ({len(df)} rows)")

    df.to_sql(
        table_name,
        destination_engine,
        schema='raw',
        if_exists='replace',
        index=False
    )

    print(f"{table_name} loaded successfully")

print("All tables loaded successfully")

Writing raw_categories to Snowflake (5 rows)
raw_categories loaded successfully
Writing raw_products to Snowflake (15 rows)
raw_products loaded successfully
Writing raw_customers to Snowflake (128 rows)
raw_customers loaded successfully
Writing raw_orders to Snowflake (567 rows)